name: update
on:
  schedule:
    - cron:  '30 1 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: install dependencies
        run: pip install -r requirements.txt
      - name: collect data
        run: ./src/main.py
      - name: commit
        uses: stefanzweifel/git-auto-commit-action@v4
